---
- name: restart pool
  hosts: all
  gather_facts: true
  vars:
    apppool: true
    apppool_name: MyAppPool1
    eventlog_log: MyCustomLog
    eventlog_source: MyCustomLog
    eventlog_msg: "Ansible Action - Restart app pool {{ apppool_name }} - Numero do Alerta {{ num_alerta }} - Ansible Job {{ awx_job_id }}"
    num_alerta: "00000"
    num_produto: "00000"
  tasks:

# Comente ou remova o bloco abaixo caso nao utilize a coleta de logs
    - name: Chamada de automacao especifica para coleta de logs geral
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-eventlog.yml

    - name: Chamada de automacao especifica para coleta de logs app pool
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-eventlog.yml

### ANTES
    - name: Obter status do pool de aplicativos antes da automacao
      win_shell: |
        $status = (Get-WebAppPoolState -Name {{ apppool_name }}).Value
        $status
      register: antes_apppool_status_result

    - name: Exibir status do pool de aplicativos antes da automacao
      debug:
        var: antes_apppool_status_result.stdout_lines

### AUTOMACAO
    - name: Return information about an existing application pool
      community.windows.win_iis_webapppool:
        name: "{{ apppool_name }}"
        state: restarted
      register: apppool_restart

### DEPOIS
    - name: Obter status do pool de aplicativos depois da automacao
      win_shell: |
        $status = (Get-WebAppPoolState -Name {{ apppool_name }}).Value
        $status
      register: depois_apppool_status_result

    - name: Exibir status do pool de aplicativos depois da automacao
      debug:
        var: depois_apppool_status_result.stdout_lines

    - name: Definindo numero do produto
      set_fact:
        num_produto: "{{ ansible_hostname | regex_search('(\\d+)(?!.*\\d)') }}"

    - name: Definir informações em uma variavel
      set_fact:
        status_automacao: |-
          ################################################
          #              STATUS DA ATIVIDADE             #
          ################################################
          Servidor Analisado/limits: {{ ansible_limit }}
          Hostname servidor: {{ ansible_hostname }}
          Versao do S.O: {{ ansible_os_name }}
          Vendor: {{ ansible_system_vendor }}
          Nome do app pool: {{ apppool_name }}
          Status APP POOL ANTES da acao ANSIBLE: {{ antes_apppool_status_result.stdout_lines }}
          Status IIS APOS a acao ANSIBLE: {{ depois_apppool_status_result.stdout_lines }}
          Numero do Alerta: {{ num_alerta }}
          Numero do produto: {{ num_produto }}
          Jod da Automação no Automation Controller: {{ awx_job_id }}
          ################################################   

    - name: Exibir banner
      debug:
        msg: "{{ status_automacao.split('\n') }}" 

    - name: Chamada de automação para escrita de logs no windows
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-write-eventlog.yml