---
- name: Create Ansible Windows event log
  hosts: windows
  gather_facts: no 
  tasks:

  - name: Write an entry to a Windows event log
    community.windows.win_eventlog_entry:
      log: MyNewLog
      source: NewLogSource1
      event_id: 1234
      message: This is a test log entry.

  - name: Add Ansible log to a Windows event log
    community.windows.win_eventlog_entry:
      log: Ansible result
      source: System
      event_id: 5555
      message: "Ansible Action"
      entry_type: Warning
      category: 5
      raw_data: 10,20
