---
- name: Create Custom Event Log and Add Entry
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create Custom Event Log
      win_shell: |
        New-EventLog -LogName "Ansible" -Source "Ansible"
      ignore_errors: yes  # Ignora erros se o log já existir

    - name: Add Entry to Custom Event Log
      win_shell: |
        Write-EventLog -LogName "Ansible" -Source "Ansible" -EventId 5555 -EntryType Warning -Message "Ansible Action"
      ignore_errors: yes  # Ignora erros se a entrada já existir