---
- name: Create Ansible Windows event log
  hosts: windows
  gather_facts: no 
  tasks:

  - name: Add a new event log with two custom sources
    community.windows.win_eventlog:
      name: Ansible
      source:
        - Ansible
      state: present

  - name: Add Ansible log to a Windows event log
    community.windows.win_eventlog_entry:
      log: Ansible
      source: Ansible
      event_id: 5555
      message: "Ansible Action"
      entry_type: Warning
      category: 5
      raw_data: 10,20
