###############################
##### PLAYBOOK TO TEST #######
###############################
---
- name: Instalação e Configuração do IIS
  hosts: all
  vars:
    apache_test_message: "Ansible!!!!"
  tasks:
    - name: Instalar o IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Instalar Recursos de Gerenciamento do IIS
      win_feature:
        name: Web-Mgmt-Console
        state: present

    - name: Colocar o arquivo index.html no servidor
      win_template:
        src: index.j2
        dest: C:\inetpub\wwwroot\index.html

    - name: Criar Pool de Aplicativos
      community.windows.win_iis_webapppool:
        name: MyAppPool
        state: present
      
    - name: Criar Pool de Aplicativos 1
      community.windows.win_iis_webapppool:
        name: MyAppPool1
        state: present

    - name: Criar Pool de Aplicativos 2
      community.windows.win_iis_webapppool:
        name: MyAppPool2
        state: present

    - name: Criar Pool de Aplicativos 3
      community.windows.win_iis_webapppool:
        name: MyAppPool3
        state: present
 
    - name: Criar diretório do site
      win_file:
        path: C:\inetpub\wwwroot\meusite
        state: directory

    - name: Criar Site no IIS
      community.windows.win_iis_website:
        name: MyWebsite
        state: started
        bindings:
          - protocol: http
            ip_address: "*"
            port: 80
        application_pool: MyAppPool
        physical_path: C:\inetpub\wwwroot\meusite  # Especifique o caminho correto aqui
        state: started
      ignore_errors: yes

    - name: Show website address
      ansible.builtin.debug:
        msg: http://{{ ansible_host }}