---
- name: Create Custom Event Log and Add Entry
  hosts: windows
  gather_facts: no
  tasks:

    - name: Write entry to custom event log
      community.windows.win_eventlog_entry:
        log: MyCustomLog
        source: Ansible
        event_id: 1234
        message: This is a test log entry.