---
- name: Create Custom Event Log and Add Entry
  hosts: windows
  gather_facts: no
  vars:
    eventlog_log: MyCustomLog
    eventlog_source: MyCustomLog
    eventlog_msg: "Ansible Action!!!"
  tasks:

    - name: Write entry to custom event log
      community.windows.win_eventlog_entry:
        log: "{{ eventlog_log }}"
        source: "{{ eventlog_source }}"
        event_id: 5555
        message: "{{ eventlog_msg }}"
        entry_type: Warning
        category: 5
        raw_data: 10,20
      ignore_errors: yes  # Ignora erros