---
- name: Create Custom Event Log and Add Entry
  hosts: windows
  gather_facts: no
  tasks:

    - name: Get-EventLog -List
      win_shell: Get-EventLog -List
      ignore_errors: yes  # Ignora erros se a entrada jรก existir

    - name: Write entry to custom event log
      community.windows.win_eventlog_entry:
        log: Windows PowerShell
        source: Ansible
        event_id: 1234
        message: This is a test log entry.