---
- name: Create Custom Event Log and Add Entry
  hosts: windows
  gather_facts: no
  tasks:
    - name: Executar script PowerShell para obter logs de eventos e fontes
      win_shell: |
        $eventLogs = Get-EventLog -List
        $logData = @()

        foreach ($log in $eventLogs) {
            $logInfo = @{
                LogName = $log.Log
                MaximumSizeKB = $log.MaximumKilobytes
                OverflowAction = $log.OverflowAction
                RetentionDays = $log.MinimumRetentionDays
                Sources = $log.Sources
            }
            $logData += $logInfo
        }

        $logData | ConvertTo-Json
      register: event_log_info

    - name: Exibir informações dos logs de eventos e fontes
      debug:
        var: event_log_info.stdout_lines

    - name: Write entry to custom event log
      community.windows.win_eventlog_entry:
        log: Windows PowerShell
        source: Ansible
        event_id: 1234
        message: This is a test log entry.