---
- name: Reciclagem Pool - Maior ofensor Memory
  hosts: windows
  gather_facts: yes
  vars:
    iis: true
    eventlog_log: MyCustomLog
    eventlog_source: MyCustomLog
    eventlog_msg: "Ansible Action - Restart IIS Web Server - Numero do Alerta {{ num_alerta }} - Ansible Job {{ awx_job_id }}"
    num_alerta: "00000"
    memory_limit: 70
  tasks:

# Comente ou remova o bloco abaixo caso nao utilize a coleta de logs
    - name: Chamada de automacao especifica para coleta de informacoes de memoria
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-mem.yml ###

    - name: Definir dados da primeira coleta de utilizacao de memoria
      set_fact:
        primeira_memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"

    # Esta tarefa encerra sessões de usuário desconectadas no Windows Server 2012 e Windows Server 2016/2019
    - name: Kill Disconnect Sessions RDP 2012 # identificar sessões de usuário desconectadas (indicadas pelo "Disc") e, em seguida, encerrá-las usando o comando logoff
      win_shell: |
        quser | Select-Object -Skip 1 | select-string "Disc"| ForEach-Object {
            $id = ($_ -split ' +')[-6]
            logoff $id
        }
      ignore_errors: true

    - name: Kill Disconnect Sessions RDP 2016/2019 # identificar sessões de usuário desconectadas (indicadas pelo "Disc") e, em seguida, encerrá-las usando o comando logoff
      win_shell: |
        quser | Select-Object -Skip 1 | select-string "Disc"| ForEach-Object {
            $id = ($_ -split ' +')[-5]
            logoff $id
        }
      ignore_errors: true

# realizar chamada de automacao para nova visão de consumo de memoria - apeas informacoes de memoria
    - name: Chamada de automacao especifica para coleta de informacoes de memoria
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-mem.yml ###
        apply:
          tags:
            - memory_report

    - name: Definir dados da segunda coleta de utilizacao de memoria
      set_fact:
        segunda_memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"

    - name: Kill process - top memory # Esta tarefa encerra o processo 'w3wp' com a maior utilização de memória.
      win_shell: |
        $id = (get-process  | where { $_.Name -eq 'w3wp'} | Sort-Object  -Property WS | Select-Object -Last 1).id
        Kill $id -Force
      when: memory_usage_percent | float > memory_limit | float
      register: kill_process_top_memory

    - name: debug
      debug:
        var: kill_process_top_memory

    - name: Chamada de automacao especifica para coleta de informacoes de memoria
      ansible.builtin.include_tasks:
        file: ../win-troubleshooting/task-win-mem.yml ###
        apply:
          tags:
            - memory_report

    - name: Definir dados da terceira coleta de utilizacao de memoria
      set_fact:
        terceira_memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"



