---
- name: Coleta de memoria dos servidores windows
  hosts: windows
  gather_facts: False
  tasks:
    - name: Obter informações de Memória 
      win_shell: |
        $memoryInfo = Get-CimInstance -ClassName Win32_OperatingSystem
        $totalMemory = $memoryInfo.TotalVisibleMemorySize
        $freeMemory = $memoryInfo.FreePhysicalMemory
        $memoryUsed = $totalMemory - $freeMemory
        $memoryUsagePercent = [math]::Round(($memoryUsed / $totalMemory) * 100, 2)

        $info = @{
          total_memory = $totalMemory
          free_memory = $freeMemory
          memory_used = $memoryUsed
          memory_usage_percent = $memoryUsagePercent
        }

        $infoJson = $info | ConvertTo-Json
        Write-Host $infoJson
      register: system_info
      changed_when: false

    - name: Extrair informações de Memória
      set_fact:
        total_memory: "{{ (system_info.stdout | from_json).total_memory }}"
        free_memory: "{{ (system_info.stdout | from_json).free_memory }}"
        memory_used: "{{ (system_info.stdout | from_json).memory_used }}"
        primeira_memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"

    - name: Listar os 10 processos que mais consomem memória
      win_shell: |
        Get-Process | Sort-Object WS -Descending | Select-Object -First 10 | Format-Table Name, WS -AutoSize | Out-String
      register: top_10_memory_processes

    - name: Exibir os 10 processos que mais consomem memória
      debug:
        var: top_10_memory_processes.stdout_lines

    - name: Listar os 5 processos que mais consomem memória
      win_shell: |
        Get-Process | Sort-Object WS -Descending | Select-Object -First 5 | Format-Table Name, WS -AutoSize | Out-String
      register: top_5_memory_processes

    - name: Exibir os 5 processos que mais consomem memória
      debug:
        var: top_5_memory_processes.stdout_lines

    - name: Listar os 3 processos que mais consomem memória
      win_shell: |
        Get-Process | Sort-Object WS -Descending | Select-Object -First 3 | Format-Table Name, WS -AutoSize | Out-String
      register: top_3_memory_processes

    - name: Exibir os 3 processos que mais consomem memória
      debug:
        var: top_3_memory_processes.stdout_lines

    - name: Get process ID
      win_shell: |
        $id = (get-process  | where { $_.Name -eq 'w3wp'} | Sort-Object  -Property WS | Select-Object -Last 1).id
        echo $id
      register: output_id_w3wp
      ignore_errors: true

    - name: Get process w3wp
      win_command: c:\windows\system32\inetsrv\appcmd.exe list wp {{ item }}
      with_items: 
          - "{{ output_id_w3wp.stdout_lines }}"
      ignore_errors: true

    - name: Get user Sessions
      win_shell: |
        quser 
      register: quser_out
      ignore_errors: true
...
