---
- name: Coleta de memoria dos servidores windows
  hosts: windows
  gather_facts: False
  tasks:
    - name: Obter informações de Memória 
      win_shell: |
        $memoryInfo = Get-CimInstance -ClassName Win32_OperatingSystem
        $totalMemory = $memoryInfo.TotalVisibleMemorySize
        $freeMemory = $memoryInfo.FreePhysicalMemory
        $memoryUsed = $totalMemory - $freeMemory
        $memoryUsagePercent = [math]::Round(($memoryUsed / $totalMemory) * 100, 2)

        $info = @{
          total_memory = $totalMemory
          free_memory = $freeMemory
          memory_used = $memoryUsed
          memory_usage_percent = $memoryUsagePercent
        }

        $infoJson = $info | ConvertTo-Json
        Write-Host $infoJson
      register: system_info
      changed_when: false
    - name: Extrair informações de Memória
      set_fact:
        total_memory: "{{ (system_info.stdout | from_json).total_memory }}"
        free_memory: "{{ (system_info.stdout | from_json).free_memory }}"
        memory_used: "{{ (system_info.stdout | from_json).memory_used }}"
        memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"
        primeira_memory_usage_percent: "{{ (system_info.stdout | from_json).memory_usage_percent }}"
      tags:
        - memory_report

    - name: informações de Memória
      debug:
        msg: "total_memory: {{ total_memory }} - free_memory: {{ free_memory }} - memory_used: {{ memory_used }} - memory_usage_percent: {{ memory_usage_percent }}"

...

