---
- name: Coletar logs de eventos do servidor Windows
  hosts: windows
  tasks:

############### System ###############
    - name: Obter logs de eventos 5 min antes e 5 minutos depois do alerta - System
      win_shell: |
        try {
          $startTime = (Get-Date).AddMinutes(-15)
          $endTime = (Get-Date).AddMinutes(-5)
          Get-WinEvent -FilterHashtable @{LogName='System'; StartTime=$startTime; EndTime=$endTime} | Format-Table -Property TimeCreated, Id, Message -AutoSize | Out-String
        } catch {
          "Nenhum evento encontrado"
        }
      register: result_System

    - name: Exibir logs coletados
      debug:
        var: result_System.stdout_lines

############### Security ###############
    - name: Obter logs de eventos 5 min antes e 5 minutos depois do alerta - Security
      win_shell: |
        try {
          $startTime = (Get-Date).AddMinutes(-15)
          $endTime = (Get-Date).AddMinutes(-5)
          Get-WinEvent -FilterHashtable @{LogName='Security'; StartTime=$startTime; EndTime=$endTime} | Format-Table -Property TimeCreated, Id, Message -AutoSize | Out-String
        } catch {
          "Nenhum evento encontrado"
        }
      register: result_Security

    - name: Exibir logs coletados
      debug:
        var: result_Security.stdout_lines

############### Application ###############
    - name: Obter logs de eventos 5 min antes e 5 minutos depois do alerta - Application
      win_shell: |
        try {
          $startTime = (Get-Date).AddMinutes(-15)
          $endTime = (Get-Date).AddMinutes(-5)
          Get-WinEvent -FilterHashtable @{LogName='Application'; StartTime=$startTime; EndTime=$endTime} | Format-Table -Property TimeCreated, Id, Message -AutoSize | Out-String
        } catch {
          "Nenhum evento encontrado"
        }
      register: result_Application

    - name: Exibir logs coletados
      debug:
        var: result_Application.stdout_lines

############### MyCustomLog ###############
    - name: Obter logs de eventos 5 min antes e 5 minutos depois do alerta - MyCustomLog
      win_shell: |
        try {
          $startTime = (Get-Date).AddMinutes(-15)
          $endTime = (Get-Date).AddMinutes(-5)
          Get-WinEvent -FilterHashtable @{LogName='MyCustomLog'; StartTime=$startTime; EndTime=$endTime} | Format-Table -Property TimeCreated, Id, Message -AutoSize | Out-String
        } catch {
          "Nenhum evento encontrado"
          exit 0
        }
      register: result_MyCustomLog


    - name: Exibir logs coletados
      debug:
        var: result_MyCustomLog.stdout_lines