---
- name: Restart IIS Web Server
  hosts: windows
  gather_facts: no 
  tasks:

    - name: Get info for a single service
      ansible.windows.win_service_info:
        name: W3SVC
      register: service_info

    - name: Start IIS Service
      win_service:
        name: W3SVC
        state: restarted

