---
- name: Restart IIS Web Server
  hosts: windows
  gather_facts: no 
  tasks:

########
# Adicionar enriquecimento dos logs e informações, essas informações podem ser enviadas para o incidente
# informacoes do incidente numero

    - name: Get info for a single service
      ansible.windows.win_service_info:
        name: W3SVC
      register: service_info
    - name: Listar eventos de erro
    
      win_shell: Get-WinEvent -LogName 'LogName' -ErrorAction SilentlyContinue | Where-Object { $_.Level -ge 2 } | Select-Object -First 10 | Format-Table -AutoSize
      register: error_logs
      failed_when: false  # Ignora erros se o log especificado não existir

    - name: Exibir eventos de erro
      debug:
        var: error_logs.stdout_lines

    - name: Obter informações do serviço IIS (W3SVC)
      win_shell: Get-Service W3SVC
      register: iis_service_info

    - name: Exibir informações do serviço IIS (W3SVC)
      debug:
        var: iis_service_info.stdout

    - name: Listar todos os logs de eventos
      win_shell: Get-WinEvent -ListLog *
      register: event_logs_info

    - name: Exibir informações dos logs de eventos
      debug:
        var: event_logs_info.stdout

    - name: Coletar os últimos logs do sistema
      win_shell: |
        Get-WinEvent -LogName System -MaxEvents 10 | Format-Table -AutoSize
      register: system_logs
      changed_when: false  # Definir como false para que não marque como alterado

    - name: Exibir os últimos logs do sistema
      debug:
        var: system_logs.stdout_lines

    - name: Start IIS Service
      win_service:
        name: W3SVC
        state: restarted

